/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AttendanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "attendanceCount"
      | "attendanceRecords"
      | "count"
      | "getAttendanceCount"
      | "getAttendanceRecord"
      | "getRegisteredUsers"
      | "getStudentAddressByMatric"
      | "getStudentByAddress"
      | "getStudentByMatric"
      | "isSystemActive"
      | "markAttendance"
      | "matricToAddress"
      | "registerUser"
      | "registeredUsers"
      | "students"
      | "toggleSystem"
      | "verifyAttendance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttendanceMarked"
      | "SystemStateChanged"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "attendanceCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attendanceRecords",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "count", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAttendanceCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttendanceRecord",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentAddressByMatric",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentByMatric",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isSystemActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markAttendance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matricToAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "students",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleSystem",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttendance",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attendanceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attendanceRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "count", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttendanceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttendanceRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentAddressByMatric",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentByMatric",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSystemActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markAttendance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matricToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "students", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttendance",
    data: BytesLike
  ): Result;
}

export namespace AttendanceMarkedEvent {
  export type InputTuple = [
    user: AddressLike,
    matricNumber: string,
    date: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    matricNumber: string,
    date: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    matricNumber: string;
    date: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SystemStateChangedEvent {
  export type InputTuple = [isActive: boolean];
  export type OutputTuple = [isActive: boolean];
  export interface OutputObject {
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    matricNumber: string,
    name: string
  ];
  export type OutputTuple = [user: string, matricNumber: string, name: string];
  export interface OutputObject {
    user: string;
    matricNumber: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Attendance extends BaseContract {
  connect(runner?: ContractRunner | null): Attendance;
  waitForDeployment(): Promise<this>;

  interface: AttendanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  attendanceCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  attendanceRecords: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, boolean, string] & {
        timestamp: bigint;
        isPresent: boolean;
        matricNumber: string;
      }
    ],
    "view"
  >;

  count: TypedContractMethod<[], [bigint], "view">;

  getAttendanceCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getAttendanceRecord: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [[bigint, boolean] & { timestamp: bigint; isPresent: boolean }],
    "view"
  >;

  getRegisteredUsers: TypedContractMethod<[], [string[]], "view">;

  getStudentAddressByMatric: TypedContractMethod<
    [matricNumber: string],
    [string],
    "view"
  >;

  getStudentByAddress: TypedContractMethod<
    [studentAddress: AddressLike],
    [
      [string, string, boolean, bigint] & {
        matricNumber: string;
        name: string;
        isRegistered: boolean;
        registrationDate: bigint;
      }
    ],
    "view"
  >;

  getStudentByMatric: TypedContractMethod<
    [matricNumber: string],
    [
      [string, string, boolean, bigint] & {
        studentAddress: string;
        name: string;
        isRegistered: boolean;
        registrationDate: bigint;
      }
    ],
    "view"
  >;

  isSystemActive: TypedContractMethod<[], [boolean], "view">;

  markAttendance: TypedContractMethod<[], [void], "nonpayable">;

  matricToAddress: TypedContractMethod<[arg0: string], [string], "view">;

  registerUser: TypedContractMethod<
    [user: AddressLike, matricNumber: string, name: string],
    [void],
    "nonpayable"
  >;

  registeredUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  students: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        matricNumber: string;
        name: string;
        isRegistered: boolean;
        registrationDate: bigint;
      }
    ],
    "view"
  >;

  toggleSystem: TypedContractMethod<[], [void], "nonpayable">;

  verifyAttendance: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "attendanceCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "attendanceRecords"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, boolean, string] & {
        timestamp: bigint;
        isPresent: boolean;
        matricNumber: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "count"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAttendanceCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAttendanceRecord"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [[bigint, boolean] & { timestamp: bigint; isPresent: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredUsers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStudentAddressByMatric"
  ): TypedContractMethod<[matricNumber: string], [string], "view">;
  getFunction(
    nameOrSignature: "getStudentByAddress"
  ): TypedContractMethod<
    [studentAddress: AddressLike],
    [
      [string, string, boolean, bigint] & {
        matricNumber: string;
        name: string;
        isRegistered: boolean;
        registrationDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudentByMatric"
  ): TypedContractMethod<
    [matricNumber: string],
    [
      [string, string, boolean, bigint] & {
        studentAddress: string;
        name: string;
        isRegistered: boolean;
        registrationDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSystemActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "markAttendance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "matricToAddress"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [user: AddressLike, matricNumber: string, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "students"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        matricNumber: string;
        name: string;
        isRegistered: boolean;
        registrationDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "toggleSystem"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyAttendance"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AttendanceMarked"
  ): TypedContractEvent<
    AttendanceMarkedEvent.InputTuple,
    AttendanceMarkedEvent.OutputTuple,
    AttendanceMarkedEvent.OutputObject
  >;
  getEvent(
    key: "SystemStateChanged"
  ): TypedContractEvent<
    SystemStateChangedEvent.InputTuple,
    SystemStateChangedEvent.OutputTuple,
    SystemStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "AttendanceMarked(address,string,uint256,uint256)": TypedContractEvent<
      AttendanceMarkedEvent.InputTuple,
      AttendanceMarkedEvent.OutputTuple,
      AttendanceMarkedEvent.OutputObject
    >;
    AttendanceMarked: TypedContractEvent<
      AttendanceMarkedEvent.InputTuple,
      AttendanceMarkedEvent.OutputTuple,
      AttendanceMarkedEvent.OutputObject
    >;

    "SystemStateChanged(bool)": TypedContractEvent<
      SystemStateChangedEvent.InputTuple,
      SystemStateChangedEvent.OutputTuple,
      SystemStateChangedEvent.OutputObject
    >;
    SystemStateChanged: TypedContractEvent<
      SystemStateChangedEvent.InputTuple,
      SystemStateChangedEvent.OutputTuple,
      SystemStateChangedEvent.OutputObject
    >;

    "UserRegistered(address,string,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
